### ISSUE TITLE
为什么在mac平台候选词不显示字根而是4个问号

### ISSUE THREAD

**Issue by eko5624** [mrshiqiqi/rime-wubi#1]
系统里已安装了`黑体字根.ttf `,如图：
<img width="337" alt="1" src="https://github.com/user-attachments/assets/956efe7c-0f65-49c5-925e-a2047a625bf2">

**Comment by eko5624** [comment]
不好意思，是我设置错误，现在可以了。

**Comment by aizigao** [comment]
我也遇到了，在 squirrel.custom.yaml 下改了一下可以生效了
patch:
  # 候选框样式
  style:
    comment_font_face: '"PingFang SC", 黑体字根
